export const GET_ORDER_LIST = 'GET_ORDER_LIST';
export const ORDER_LOADING = 'ORDER_LOADING';
export const GET_ORDER_ITEM = 'GET_ORDER_ITEM';
export const ORDER_ITEM_UPDATE = 'ORDER_ITEM_UPDATE';
export const ORDER_ITEM_IN_ACTIVE = 'ORDER_ITEM_IN_ACTIVE';
export const ORDER_CREATE = 'ORDER_CREATE';
export const ORDERS_IS_UPDATE = 'ORDERS_IS_UPDATE';

export const ORDER_IS_CREATE = 'ORDER_IS_CREATE';
export const ORDER_IS_UPDATE = 'ORDER_IS_UPDATE';
export const ORDER_IS_SEND = 'ORDER_IS_SEND';
