export const MODAL_SET_VISIBLE = 'PUBLIC_MODAL_SET_VISIBLE';
export const MODAL_SET_PROPS_MODAL = 'PUBLIC_MODAL_SET_PROPS_MODAL';
export const MODAL_SET_OK_FUNC = 'PUBLIC_MODAL_SET_OK_FUNC';
export const MODAL_SET_CANCEL_FUNC = 'PUBLIC_MODAL_SET_CANCEL_FUNC';
