export const MODAL_SET_VISIBLE = 'MODAL_SET_VISIBLE';
export const MODAL_SET_PROPS_MODAL = 'MODAL_SET_PROPS_MODAL';
export const MODAL_SET_OK_FUNC = 'MODAL_SET_OK_FUNC';
export const MODAL_SET_CANCEL_FUNC = 'MODAL_SET_CANCEL_FUNC';
